/**
 * Mirrors CloudinaryService.publicIdFromUrl on the server exactly — every
 * business photo URL this app ever displays was generated by that service
 * with this literal prefix baked in via cloudinary.url({fetch_format:'auto',
 * quality:'auto'}). Returns null for any URL that isn't ours (shouldn't
 * happen for photos this app uploaded, but a stale/legacy URL is handled
 * gracefully rather than throwing).
 */
const DELIVERY_PREFIX = "/image/upload/f_auto,q_auto/";

export function cloudinaryPublicIdFromUrl(url: string): string | null {
  const idx = url.indexOf(DELIVERY_PREFIX);
  return idx === -1 ? null : url.slice(idx + DELIVERY_PREFIX.length);
}
