import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsIn,
  IsInt,
  IsOptional,
  IsString,
  Matches,
  Max,
  MaxLength,
  Min,
  MinLength,
  ValidateNested,
} from 'class-validator';

const TIME_12H = /^(0?[1-9]|1[0-2]):[0-5][0-9]\s?(AM|PM)$/i;
const DATE_ISO = /^\d{4}-\d{2}-\d{2}$/;
const PAYMENT_METHODS = ['wallet', 'esewa', 'khalti', 'connectips', 'imepay', 'card', 'cash'];
// Seat labels are generated by the client as `${row}${col}` with col ∈ A–D
// (see client/src/features/buses/types.ts → generateSeats). The server must
// enforce the same shape — previously any arbitrary string was accepted and
// written into booked_seats, corrupting seat inventory.
const SEAT_LABEL = /^[1-9]\d?[A-Da-d]$/;

export class PassengerDto {
  @IsString()
  @MinLength(1)
  firstName!: string;

  @IsString()
  @MinLength(1)
  lastName!: string;

  @IsString()
  email!: string;

  @IsString()
  phone!: string;

  @IsInt()
  @Min(1)
  age!: number;

  @IsIn(['male', 'female', 'other'])
  gender!: 'male' | 'female' | 'other';
}

export class BookBusDto {
  @IsArray()
  @ArrayMinSize(1, { message: 'Select at least one seat.' })
  @ArrayMaxSize(6, { message: 'You can book at most 6 seats per booking.' })
  @IsString({ each: true })
  @Matches(SEAT_LABEL, { each: true, message: 'One or more seat labels are invalid.' })
  seats!: string[];

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => PassengerDto)
  passengers!: PassengerDto[];

  @IsIn(PAYMENT_METHODS)
  method!: string;
}

export class RegisterBusDto {
  @IsString()
  @MinLength(1)
  busName!: string;

  @IsString()
  @MinLength(1)
  busNumber!: string;

  @IsString()
  @MinLength(1)
  registrationNo!: string;

  @IsString()
  @MinLength(1)
  type!: string;

  @IsString()
  @MinLength(1)
  fuelType!: string;

  @IsInt()
  @Min(4)
  @Max(80)
  totalSeats!: number;

  @IsOptional()
  @IsInt()
  @Min(1, { message: 'totalRows must be at least 1.' })
  totalRows?: number;

  @IsArray()
  @IsString({ each: true })
  amenities!: string[];
}

export class CreateScheduleDto {
  @IsString()
  busId!: string;

  @IsString()
  @MinLength(1)
  fromCity!: string;

  @IsString()
  @MinLength(1)
  toCity!: string;

  @Matches(TIME_12H, { message: 'departureTime must look like "07:00 AM".' })
  departureTime!: string;

  @Matches(TIME_12H, { message: 'arrivalTime must look like "07:00 AM".' })
  arrivalTime!: string;

  @Type(() => Number)
  @Min(1)
  price!: number;

  @IsIn(['once', 'daily', 'weekly'])
  frequency!: 'once' | 'daily' | 'weekly';

  @IsOptional()
  @Matches(DATE_ISO)
  onceDate?: string;

  @IsOptional()
  @IsArray()
  @IsInt({ each: true })
  @Min(0, { each: true })
  @Max(6, { each: true })
  operatingDays?: number[];

  @IsOptional()
  @Matches(DATE_ISO)
  validFrom?: string;

  @IsOptional()
  @Matches(DATE_ISO)
  validUntil?: string;
}

export class UpdateTripStatusDto {
  @IsIn(['scheduled', 'cancelled', 'completed'])
  status!: 'scheduled' | 'cancelled' | 'completed';
}

/** Customer rates a completed intercity bus trip. One review per ticket. */
export class CreateTicketReviewDto {
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(5)
  rating!: number;

  @IsOptional()
  @IsString()
  @MaxLength(1000)
  comment?: string;
}

export class CancelTicketDto {
  @IsOptional()
  @IsString()
  @MaxLength(300)
  reason?: string;
}