/**
 * Standalone migration runner: `npm run db:migrate`.
 *
 * Applies every pending migration in ./drizzle (generated by
 * `npm run db:generate`) against DATABASE_URL. Safe to run repeatedly —
 * drizzle tracks applied migrations in a `__drizzle_migrations` table.
 */
import 'dotenv/config';
import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';

async function main() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error('DATABASE_URL is not set. Copy .env.example to .env and fill it in.');
  }

  const pool = new Pool({ connectionString, max: 1 });
  const db = drizzle(pool);

  console.log('[migrate] applying pending migrations...');
  await migrate(db, { migrationsFolder: './drizzle' });
  console.log('[migrate] done.');

  await pool.end();
}

main().catch((err) => {
  console.error('[migrate] failed:', err);
  process.exit(1);
});
