import {
  AlertTriangle,
  ArrowLeftRight,
  Banknote,
  Bed,
  BedDouble,
  BellRing,
  Bike,
  BrainCircuit,
  Building2,
  Bus,
  CalendarCheck,
  CalendarClock,
  CalendarRange,
  Car,
  ClipboardList,
  Cross,
  Droplets,
  FileCheck,
  Gauge,
  Gavel,
  KeyRound,
  LayoutGrid,
  LayoutTemplate,
  LifeBuoy,
  Map,
  MapPin,
  Milestone,
  Monitor,
  MoreHorizontal,
  Mountain,
  Navigation,
  Package,
  PackageSearch,
  Route,
  ScrollText,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShoppingBasket,
  Sparkles,
  Star,
  Ticket,
  TrendingUp,
  Truck,
  User,
  UserPlus,
  Users,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wind,
  Zap,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

interface IconProps extends LucideProps {
  name: string;
}

/**
 * Render a lucide icon by string name. Only the icons actually referenced
 * across the app are registered here so the bundle stays lean (importing the
 * full lucide barrel pulls in ~1,500 icons).
 */
const REGISTRY: Record<string, LucideIcon> = {
  AlertTriangle,
  ArrowLeftRight,
  Banknote,
  Bed,
  BedDouble,
  BellRing,
  Bike,
  BrainCircuit,
  Building2,
  Bus,
  CalendarCheck,
  CalendarClock,
  CalendarRange,
  Car,
  ClipboardList,
  Cross,
  Droplets,
  FileCheck,
  Gauge,
  Gavel,
  KeyRound,
  LayoutGrid,
  LayoutTemplate,
  LifeBuoy,
  Map,
  MapPin,
  Milestone,
  Monitor,
  MoreHorizontal,
  Mountain,
  Navigation,
  Package,
  PackageSearch,
  Route,
  ScrollText,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShoppingBasket,
  Sparkles,
  Star,
  Ticket,
  TrendingUp,
  Truck,
  User,
  UserPlus,
  Users,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wind,
  Zap,
};

export function Icon({ name, ...props }: IconProps) {
  const Cmp = REGISTRY[name];
  if (!Cmp) return null;
  return <Cmp {...props} />;
}
